[package]
name = "day7"
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
itertools = "0.13.0"

[lints]
workspace = true
