[package]
name = "day1"
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true

[lints]
workspace = true