[package]
name = "day4"
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
regex = "1.11.1"

[lints]
workspace = true
